kind: pipeline
name: default

# 使用 x86_64
# platform:
#   os: linux
#   arch: amd64

# clone 條件
clone:
  # 只取得最近一次commit
  # depth: 1
  # 不拉取
  disable: true

# 工作目錄
# workspace:
#   path: /var/www/html

steps:
  # 取得 cache vendor 檔案
  # - name: rebuild-cache
  #   image: drillster/drone-volume-cache
  #   pull: if-not-exists
  #   volumes:
  #     - name: cache
  #       path: /cache
  #   settings:
  #     rebuild: true
  #     mount:
  #       - ./vendor

  # 使用 laradock PHP 8.1 進行 unit test (需要把拉取打開)
  # - name: unit test
  #   # 不存在才拉取
  #   pull: if-not-exists
  #   image: laradock/workspace:latest-8.1
  #   commands:
  #     - php -v
  #     - composer -V
  #     - composer install --prefer-dist
  #     - cp .env.ci .env
  #     - php artisan optimize:clear
  #     - ./vendor/bin/pest --profile

  # 重建 vendor cache
  # - name: rebuild-cache
  #   image: drillster/drone-volume-cache
  #   pull: if-not-exists
  #   volumes:
  #     - name: cache
  #       path: /cache
  #   settings:
  #     rebuild: true
  #     mount:
  #       - ./vendor

  - name: deploy
    image: ghcr.io/appleboy/drone-ssh
    # 不存在才拉取
    pull: if-not-exists
    # 當branch為main時才執行
    when:
      branch:
        - main
    # 定義環境變數
    environment:
      # 這邊要大寫
      PROJECT_PATH:
        from_secret: PROJECT_PATH
    settings:
      host:
        from_secret: SSH_HOST
      username:
        from_secret: SSH_USERNAME
      key:
        from_secret: SSH_PRIVATE_KEY
      port: 22
      command_timeout: 2m
      envs:
        # 這邊要小寫，然後在 script 裡要大寫
        - project_path
      script:
        - cd $PROJECT_PATH
        # 拉取
        - git pull
        # 設定權限
        - chown nginx:nginx -R $PROJECT_PATH
        - chmod 775 -R $PROJECT_PATH
        - ls -l
        # 顯示最後5筆commit
        - git --no-pager log --decorate=short --pretty=oneline -n5 | cut -c 1-$COLUMNS
# 快取 volumes
# volumes:
#   - name: cache
#     host:
#       path: /tmp/cache

# 觸發 pipeline 的條件，如果是在 steps 內可使用 when
trigger:
  branch:
    - main
